### ISSUE TITLE
display_call_args is broken

### ISSUE THREAD

**Issue by nedwill** [BinaryAnalysisPlatform/qira#108]
For some reason the function argument recovery code is broken. I wouldn't be surprised if we had a regression after moving to BAP as the code seems to rely heavily on architecture-dependent constants.

**Comment by geohot** [comment]
lol yea, blame tyler

**Comment by nedwill** [comment]
So I finally got some time to look at this and it actually seems to work out. My bad. Because we don't get arguments for library functions if we don't trace them, we just miss all of them and I thought it was broken. That code could definitely be cleaned up a bit as I find the filter and map functions pretty unreadable (compared to list comprehensions), but that's a matter of taste.
