### ISSUE TITLE
PIE binaries don't work without --tracelibraries

### ISSUE THREAD

**Issue by nedwill** [BinaryAnalysisPlatform/qira#110]
I got an email from a QIRA user that the `okami` challenge from UIUCTF wasn't working, and it seems broken to me too. QEMU seems to trace it but nothing shows up in the DB. I'll try to find and squash the bug soon as we have a CTF this weekend.

Here's the binary: [okami](https://github.com/ctfs/write-ups-2015/blob/master/uiuctf-2015/pwn/okami/okami1)

**Comment by nedwill** [comment]
This is happening because things are getting filtered that aren't supposed to be as the binary is PIE.

**Comment by geohot** [comment]
Yea, that's a known bug, you can run with "-t", but then you get libc too. This should be fixed by getting the program regions instead of the if statement hack in QEMU

**Comment by nedwill** [comment]
Yeah I saw that. Not sure how straight forward it is to get that from QEMU but I've done it in PIN and DynamoRIO and it was super easy. We can try to fix the hack soon.

**Comment by tim-becker** [comment]
This is closed by #115.

**Comment by nedwill** [comment]
Yeah, nice work.

**Comment by yeuchimse** [comment]
It seems that this issue remains unsolved. Run qira with [*cards*](https://mega.nz/#!dYMTjZgC!1UVo7B8hclg0qSrrQsXNcoXWDN6n97q4PWKkvxqdRZI) challenge from *9447 CTF* still shows nothing in the browser.

![2015-11-30_10-21-14](https://cloud.githubusercontent.com/assets/3500582/11462842/20607dc8-974c-11e5-92e6-168830a5de94.png)

**Comment by nedwill** [comment]
Are you sure you're running the latest build? It seems to work on my end.
![2015-11-29-225847_1107x1090_scrot](https://cloud.githubusercontent.com/assets/3682087/11463226/d8c9a278-96ec-11e5-98a1-e8a5201fbb82.png)

**Comment by yeuchimse** [comment]
Yeah, after reinstalling QEMU, everything works fine. Love you ^^
