### ISSUE TITLE
qira result doesn't appear in chrome browser...

### ISSUE THREAD

**Issue by cronos91** [BinaryAnalysisPlatform/qira#126]
qira result doesn't appear in chrome browser...

WHY?

please, help!

**Comment by ww9210** [comment]
I have the same issue, using the following command  get only the qira framework in the browser, no register and memory dump is available.
 qira -s --web-host 172.18.18.52  --flush-cache "./readable"

**Comment by nedwill** [comment]
This is likely related to issue #120. I've looked at this briefly earlier in the week and it's hard to tell what's going on. It seems like some annoying Websockets bug (new version of Chrome? Old QIRA 1.1 seems broken in my VM too.). I'm still looking.

**Comment by bananaappletw** [comment]
It is likely js problem in socket.io.min.js file.
Open the Chrome could see the error message.
I change this file to 1.3.7 version and it work fine.
But the run_test.sh command failed and some files depend on this file failed.

**Comment by nedwill** [comment]
@bananaappletw Nice find! I actually had updated this when I was trying to debug before and had the same issue with dependencies, but since it looks like the current `socket.io.min.js` is just completely broken, we'll have to put up with it.

**Comment by nedwill** [comment]
It seems like the WebSockets standard is now finalized, and Chrome updated accordingly. Therefore we had to update socket.io.min.js and phantomjs in order to get QIRA working again. If you see any other issues, please let me know. Thanks for the report!

**Comment by T3KT4K** [comment]
I am actually still suffering from this issue, but I'm running Iceweasel! Is it still the websockets issue?

**Comment by stefan2904** [comment]
Well, I guess the version on the homepage is not the newest one, so it's probably not yet fixed there?

**Comment by stkim1** [comment]
This still is an issue. 

1. ida client tries to open WebSocket port [`3003`](https://github.com/BinaryAnalysisPlatform/qira/blob/master/web/client/ida.js#L5) meanwhile `Qira` serves a WebSocket on `4000`. 
2. Once that's fixed, Chrome complains with `Error during WebSocket handshake: Invalid status line`.

**Environment** : OSX 10.11.4  
**Chrome** : 50.0.2661.86 (64-bit)  
**Qira** : freshly cloned from repo today.

**Comment by Maroc-OS** [comment]
If i still remember this isn't an issue cause the plugin have server/client
and this i te default plugin ports not related to chrom one. If am not
Wrong, you should see that on the plugin client/server codes.

On Wednesday, April 27, 2016, Sung-Taek, Kim <notifications@github.com>
wrote:

> This still is an issue.
>
>    1. ida client tries to open WebSocket port 3003
>    <https://github.com/BinaryAnalysisPlatform/qira/blob/master/web/client/ida.js#L5>
>    meanwhile Qira serves a WebSocket on 4000.
>    2. Once that's fixed, Chrome complains with Error during WebSocket
>    handshake: Invalid status line.
>
> *Environment* : OSX 10.11.4
>
> *Chrome* : 50.0.2661.86 (64-bit)
>
> *Qira* : freshly cloned from repo today.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BinaryAnalysisPlatform/qira/issues/126#issuecomment-215141100>
>


-- 
-- 
-----------------------------------------
Merruk Technology, SARL.
0 (5) 26 96 59 08
www.merruk.com

**Comment by stkim1** [comment]
@Maroc-OS 

Ok, Could you be kind enough to show me where to look please?

**Comment by stkim1** [comment]
@Maroc-OS

> If i still remember this isn't an issue cause the plugin have server/client and this i te default plugin ports not related to chrom one. If am not Wrong, you should see that on the plugin client/server codes.

Sorry. I don't follow you. It would be actually helpful if you could write in a clean phrase. Could you point what server/client plugin I need to look into to?

@nedwill 

I've tested with Firefox 45.0.2 and Safari `Version 9.1 (11601.5.17.1)` and neither of them is working. Could you please take a look into the issue again?
