### ISSUE TITLE
qira.me/dl should be HTTPS

### ISSUE THREAD

**Issue by comex** [BinaryAnalysisPlatform/qira#136]
Fears of "paste into terminal to install" scripts are typically somewhat overblown, but these days I'd say HTTPS is a must.

**Comment by nedwill** [comment]
@geohot You own the webserver, hopefully you can enable https.

**Comment by nedwill** [comment]
On top of that, we should look at cleaning up the install scripts to assuage the frustrations some of the people who are more picky about how things are packaged (seen on a hackernews post). And it might be possible to get this in the default repos as a result.

**Comment by geohot** [comment]
Changed default install to be "1.2", which is much much larger than it needs to be and terrible. But I agree 1.0 has gone sort of stale.

**Comment by nedwill** [comment]
@geohot It looks like qira.me isn't updated with the new instructions.

**Comment by geohot** [comment]
hmm, it should be, looks fine on my phone...refresh it

**Comment by nedwill** [comment]
Yeah it was cached for me, sorry for the bogus complaint.
