### ISSUE TITLE
Qiradb compile time problem

### ISSUE THREAD

**Issue by Maroc-OS** [BinaryAnalysisPlatform/qira#145]
Qiradb library have an issue of comparison between signed and unsigned int, when compiling with default compiler, and have also a warning about cpp non valid option passed to the compiler.

```
cc1plus: **warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++**
    qiradb/Trace.cpp: In member function ‘bool Trace::remap_backing(uint64_t)’:
    qiradb/Trace.cpp:112:12: **warning: comparison between signed and unsigned integer expressions [-Wsign-compare]**
         if (fs < new_size) {
                ^
    qiradb/Trace.cpp: In member function ‘void Trace::process()’:
    qiradb/Trace.cpp:199:35: **warning: comparison between signed and unsigned integer expressions [-Wsign-compare]**
         if (type == 'W' && c->address < (register_size_ * register_count_)) {
                                       ^
    g++ -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c qiradb/_qiradb.cpp -o build/temp.linux-x86_64-2.7/qiradb/_qiradb.o
    cc1plus: **warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++**
```

But using clang as default compiler for only this particular python lib fix both problems. the problem is this will make clang a dependency for the project.

a PR is ready if that's not a problem

**Comment by geohot** [comment]
Switching to clang to fix warnings seems like overkill, can they be fixed with casts?

**Comment by Maroc-OS** [comment]
yes i agree, the problem is for -Wstrict-prototypes it's python related "setuptools" what i did was creating a new python envirement variable for cc/cxx compilers and make them "clang++". this only works for this particular python package. but at the end i agree whith what you said.

**Comment by Maroc-OS** [comment]
BTW, could you see PR 144.

**Comment by Maroc-OS** [comment]
FIX here https://github.com/Maroc-OS/qira/commit/e055baa996a98845c4590142d661af37e9cb0a91

PR #148

**Comment by Maroc-OS** [comment]
it seems okay closing the issue
