### ISSUE TITLE
QIRA use tuples on REGS inside arch.py 

### ISSUE THREAD

**Issue by Maroc-OS** [BinaryAnalysisPlatform/qira#147]
Why are we using that? this makes the vars static, if we have discoveries like detecting endianess etc we can't assign to the regs.

**Comment by nedwill** [comment]
Yeah, it's possible for ARM to have big/little endian. For now I think we just assume little endian binaries but this would be a welcome fix. Switching to a list would be the easiest first thing to do. Maybe we should go further and make a dict or class for this? It's a design choice, @geohot what do you think?

**Comment by nedwill** [comment]
Now that I think about it, perhaps endianness should be factored out of arch.py rather than making those tuples mutable, as endianness is needed on the frontend to display the information correctly, but it's not actually needed as part of the information about what an arch is

**Comment by Maroc-OS** [comment]
> Now that I think about it, perhaps endianness should be factored out of arch.py rather than making those tuples mutable, as endianness is needed on the frontend to display the information correctly, but it's not actually needed as part of the information about what an arch is

Exactely. I agree with that.

**Comment by Maroc-OS** [comment]
merged by @geohot issue closed
