### ISSUE TITLE
Compilation Failed

### ISSUE THREAD

**Issue by d0lph1n98** [BinaryAnalysisPlatform/qira#160]
`make install` output:

> qemu-img.c: In function ‘compare_data’:
qemu-img.c:61:5: warning: implicit declaration of function ‘g_strcmp0’ [-Wimplicit-function-declaration]
     return g_strcmp0(a, b);
     ^
qemu-img.c:61:5: warning: nested extern declaration of ‘g_strcmp0’ [-Wnested-externs]
qemu-img.c: In function ‘add_format_to_seq’:
qemu-img.c:71:5: error: unknown type name ‘GSequence’
     GSequence *seq = opaque;
     ^
qemu-img.c:73:5: warning: implicit declaration of function ‘g_sequence_insert_sorted’ [-Wimplicit-function-declaration]
     g_sequence_insert_sorted(seq, (gpointer)fmt_name,
     ^
qemu-img.c:73:5: warning: nested extern declaration of ‘g_sequence_insert_sorted’ [-Wnested-externs]
qemu-img.c: In function ‘help’:
qemu-img.c:159:5: error: unknown type name ‘GSequence’
     GSequence *seq;
     ^
qemu-img.c:162:5: warning: implicit declaration of function ‘g_sequence_new’ [-Wimplicit-function-declaration]
     seq = g_sequence_new(NULL);
     ^
qemu-img.c:162:5: warning: nested extern declaration of ‘g_sequence_new’ [-Wnested-externs]
qemu-img.c:162:9: warning: assignment makes pointer from integer without a cast [enabled by default]
     seq = g_sequence_new(NULL);
         ^
qemu-img.c:164:5: warning: implicit declaration of function ‘g_sequence_foreach’ [-Wimplicit-function-declaration]
     g_sequence_foreach(seq, print_format, NULL);
     ^
qemu-img.c:164:5: warning: nested extern declaration of ‘g_sequence_foreach’ [-Wnested-externs]
qemu-img.c:166:5: warning: implicit declaration of function ‘g_sequence_free’ [-Wimplicit-function-declaration]
     g_sequence_free(seq);
     ^
qemu-img.c:166:5: warning: nested extern declaration of ‘g_sequence_free’ [-Wnested-externs]
make: *** [qemu-img.o] Error 1
make: *** Waiting for unfinished jobs....

`lsb_release -a` output: 

> Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

Also there are two Python ImportError even though i already install it via `pip install --upgrade -r requirements.txt`.

**Comment by geohot** [comment]
Hmm, seems like a qemu build problem. Can you build qemu outside of qira? We might have to update the version.

**Comment by d0lph1n98** [comment]
It seems there are some conflicts with the patch. I tried again with the latest version which is qemu-2.5.1 and the compilation succeeded without the patch but with the patch i got this output:

> path/to/qira/tracers/qemu/qemu-latest/tci.c:852:6: error: conflicting types for ‘target_disas’
 void target_disas(FILE *out, CPUArchState *env, target_ulong code, target_ulong size, int flags) {
      ^
In file included from path/to/qira/tracers/qemu/qemu-latest/include/qemu/log.h:10:0,
                 from path/to/qira/tracers/qemu/qemu-latest/include/exec/exec-all.h:67,
                 from path/to/qira/tracers/qemu/qemu-latest/target-i386/cpu.h:1229,
                 from path/to/qira/tracers/qemu/qemu-latest/include/qemu-common.h:53,
                 from path/to/qira/tracers/qemu/qemu-latest/tci.c:27:
path/to/qira/tracers/qemu/qemu-latest/include/disas/disas.h:9:6: note: previous declaration of ‘target_disas’ was here
 void target_disas(FILE *out, CPUState *cpu, target_ulong code,
      ^
path/to/qira/tracers/qemu/qemu-latest/tci.c:852:6: error: conflicting types for ‘target_disas’
 void target_disas(FILE *out, CPUArchState *env, target_ulong code, target_ulong size, int flags) {
      ^
In file included from path/to/qira/tracers/qemu/qemu-latest/include/qemu/log.h:10:0,
                 from path/to/qira/tracers/qemu/qemu-latest/include/exec/exec-all.h:67,
                 from path/to/qira/tracers/qemu/qemu-latest/target-ppc/cpu.h:2336,
                 from path/to/qira/tracers/qemu/qemu-latest/include/qemu-common.h:53,
                 from path/to/qira/tracers/qemu/qemu-latest/tci.c:27:
path/to/qira/tracers/qemu/qemu-latest/include/disas/disas.h:9:6: note: previous declaration of ‘target_disas’ was here
 void target_disas(FILE *out, CPUState *cpu, target_ulong code,
      ^
make[1]: *** [tci.o] Error 1
make: *** [subdir-i386-linux-user] Error 2
make: *** Waiting for unfinished jobs....
  CC    ppc-linux-user/tcg/tcg-common.o
make[1]: *** [tci.o] Error 1
make[1]: *** Waiting for unfinished jobs....
  CC    x86_64-linux-user/tci.o
make: *** [subdir-ppc-linux-user] Error 2
  CC    x86_64-linux-user/tcg/tcg-common.o
  CC    x86_64-linux-user/disas/tci.o
path/to/qira/tracers/qemu/qemu-latest/tci.c:852:6: error: conflicting types for ‘target_disas’
 void target_disas(FILE *out, CPUArchState *env, target_ulong code, target_ulong size, int flags) {
      ^
In file included from path/to/qira/tracers/qemu/qemu-latest/include/qemu/log.h:10:0,
                 from path/to/qira/tracers/qemu/qemu-latest/include/exec/exec-all.h:67,
                 from path/to/qira/tracers/qemu/qemu-latest/target-i386/cpu.h:1229,
                 from path/to/qira/tracers/qemu/qemu-latest/include/qemu-common.h:53,
                 from path/to/qira/tracers/qemu/qemu-latest/tci.c:27:
path/to/qira/tracers/qemu/qemu-latest/include/disas/disas.h:9:6: note: previous declaration of ‘target_disas’ was here
 void target_disas(FILE *out, CPUState *cpu, target_ulong code,
      ^
make[1]: *** [tci.o] Error 1
make[1]: *** Waiting for unfinished jobs....
  CC    arm-linux-user/tci.o
  CC    arm-linux-user/tcg/tcg-common.o
  CC    arm-linux-user/disas/tci.o
make: *** [subdir-x86_64-linux-user] Error 2
  CC    arm-linux-user/fpu/softfloat.o
  CC    arm-linux-user/disas.o
path/to/qira/tracers/qemu/qemu-latest/tci.c:852:6: error: conflicting types for ‘target_disas’
 void target_disas(FILE *out, CPUArchState *env, target_ulong code, target_ulong size, int flags) {
      ^
In file included from path/to/qira/tracers/qemu/qemu-latest/include/qemu/log.h:10:0,
                 from path/to/qira/tracers/qemu/qemu-latest/include/exec/exec-all.h:67,
                 from path/to/qira/tracers/qemu/qemu-latest/target-arm/cpu.h:1986,
                 from path/to/qira/tracers/qemu/qemu-latest/include/qemu-common.h:53,
                 from path/to/qira/tracers/qemu/qemu-latest/tci.c:27:
path/to/qira/tracers/qemu/qemu-latest/include/disas/disas.h:9:6: note: previous declaration of ‘target_disas’ was here
 void target_disas(FILE *out, CPUState *cpu, target_ulong code,
      ^
path/to/qira/tracers/qemu/qemu-latest/tci.c: In function ‘tcg_qemu_tb_exec’:
path/to/qira/tracers/qemu/qemu-latest/tci.c:1070:28: warning: variable ‘a’ set but not used [-Wunused-but-set-variable]
             struct change *a = NULL;
                            ^
  GEN   arm-linux-user/gdbstub-xml.c
make[1]: *** [tci.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [subdir-arm-linux-user] Error 2

**Comment by nedwill** [comment]
@d0lph1n98 
To be clear, you applied the patch off the latest master as updated by #164?
If so, please let me know what OS/compiler you're running so I can replicate the problem.

**Comment by d0lph1n98** [comment]
@nedwill The problem is solved with the new patch using qemu-2.5.1, no more conflicts and the compilation succeeded very well.
