### ISSUE TITLE
Update QEMU_VERSION=2.1.3 to 2.5.1?

### ISSUE THREAD

**Issue by rain-1** [BinaryAnalysisPlatform/qira#162]
Hello!

Is there any interest in updating the version of qemu? Currently qira is pointing to a really old version and, when building it, the tests fail for me. Of course the patch fails to apply to the newer version. So it's a bit difficult.

What do you think?

* https://github.com/BinaryAnalysisPlatform/qira/blob/master/tracers/qemu_build.sh#L6
* https://github.com/BinaryAnalysisPlatform/qira/blob/master/tracers/qemu.patch

**Comment by geohot** [comment]
If you fix it, test it, and send along a good pull request, we'd be happy to merge :)

**Comment by rain-1** [comment]
Sure! https://github.com/BinaryAnalysisPlatform/qira/pull/164
