### ISSUE TITLE
Fix: Firefox support

### ISSUE THREAD

**Issue by Namalee** [BinaryAnalysisPlatform/qira#165]
To allow the 'K' and 'J' support in Firefox, into web/client/controls.js, line 133 (on current version) : 

add e.preventDefault(); at the beginning of the function like this
`window.onkeydown = function(e) {
e.preventDefault();
//p(e.keyCode); ....`

**Comment by geohot** [comment]
Submit a pull request, will merge.

**Comment by Namalee** [comment]
done ;)

**Comment by Namalee** [comment]
Pull request merged, case closed.

Thanks.
