### ISSUE TITLE
qira and windows binaries

### ISSUE THREAD

**Issue by n4x0r** [BinaryAnalysisPlatform/qira#179]
Is there any way to make qira run with windows binaries?. when i try it, it just sets the server but nothing really happens. Is there anything im missing?.

Regards

**Comment by IgnacioSanmillan** [comment]
can someone give me any examples on how to use --pin in qira in order to degub windows binaries?

**Comment by Maroc-OS** [comment]
In windows it works natively, for *nix use wine. I didn't tried pin on linux

On Saturday, June 11, 2016, n4x <notifications@github.com> wrote:

> can someone give me any examples on how to use --pin in qira in order to
> degub windows binaries?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BinaryAnalysisPlatform/qira/issues/179#issuecomment-225395392>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABg9mGNv78rrO4eO5PICaiSa4Fw4pWphks5qKyfrgaJpZM4Izo0l>
> .
>


-- 
-- 
-----------------------------------------
Merruk Technology, SARL.
0 (5) 26 96 59 08
www.merruk.com

**Comment by IgnacioSanmillan** [comment]
I have installed qira in the linux subsystem in windows 10, is there any chance that i can use pin natively while keeping qira on the linux subsystem? 
moreover would you plase post some example commands of qira --pin since theres no documentationon how to use it.

Regards

**Comment by IgnacioSanmillan** [comment]
I have installed qira in the windows 10 linux subsystem since the qira.bat was unable to install it natively in windows. I have tried to use wine in linux, but wira will only trace wine, is there any better way to do it?

**Comment by IgnacioSanmillan** [comment]
the error that install.bat gaves me is the following: 
error: can't copy 'src\build\capstone.dll' : doesn't exist or not regular file
:S

**Comment by IgnacioSanmillan** [comment]
How does qira debug windows applications natively, because for the release of qira that i have it does not work. Ive installed qira with the install.bat, and still says loader error: Non-Elf binary.

**Comment by IgnacioSanmillan** [comment]
![photo_2016-06-12_04-14-13](https://cloud.githubusercontent.com/assets/14844304/15988517/26fbf18e-3054-11e6-81bb-ebb838777571.jpg) Also it seems that the web server is not addapted fro windows since i get this error while trying to run qira

**Comment by wy666444** [comment]
\qira\middleware\qira_webserver.py:41: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  from flask.ext.socketio import SocketIO, emit
*** program is C:\Users\wy\Desktop\魔鬼训练营\工具\qira\stack1 with hash 81d1adbda5c66b08eb76d3c1a43960f529337028
Traceback (most recent call last):
  File "middleware/qira.py", line 83, in <module>
    program = qira_program.Program(args.binary, args.args, qemu_args)
  File "C:\Users\wy\Desktop\魔鬼训练营\工具\qira\middleware\qira_program.py", line 56, in __init__
    self.static = static2.Static(self.program)
  File "C:\Users\wy\Desktop\魔鬼训练营\工具\qira/static2\static2.py", line 108, in __init__
    loader.load_binary(self)
  File "C:\Users\wy\Desktop\魔鬼训练营\工具\qira\static2\builtin\loader.py", line 84, in load_binary
    for nsym, symbol in enumerate(section.iter_symbols()):
  File "C:\Python27\lib\site-packages\elftools\elf\sections.py", line 124, in iter_symbols
    yield self.get_symbol(i)
  File "C:\Python27\lib\site-packages\elftools\elf\sections.py", line 101, in get_symbol
    stream_pos=entry_offset)
  File "C:\Python27\lib\site-packages\elftools\common\utils.py", line 34, in struct_parse
    raise ELFParseError(str(e))
elftools.common.exceptions.ELFParseError: expected 4, found 0

**Comment by wy666444** [comment]
why ,don't run

**Comment by tho-maj** [comment]
I can't find the install.bat file.
