### ISSUE TITLE
BAP install takes so much time

### ISSUE THREAD

**Issue by geohot** [BinaryAnalysisPlatform/qira#69]
This is fine for trunk builds, but this won't fly for releases. Not sure my bdistrib.sh script even close to works anymore, but if we want to ship a release, this is one of the roadblocks. Shipping binaries in release is fine.

**Comment by ivg** [comment]
this is a blocker for binary distribution BinaryAnalysisPlatform/bap#64.

In short, bap uses plugin system, where plugins are just .so files. And currently search path is compiled into source. As soon as I fix this, bap can be easily distributed a binary.
