### ISSUE TITLE
Add automatic testing stuff to Travis + Document new testing stuff

### ISSUE THREAD

**Issue by geohot** [BinaryAnalysisPlatform/qira#70]
Documentation doesn't have to be much, just a couple of lines in the README.

Also, I added you to BinaryAnalysisPlatform, you are now the 2nd biggest contributor to QIRA, and have the right to merge sensible pull requests.

**Comment by nedwill** [comment]
I'll have it done soon. Thanks for adding me.

**Comment by nedwill** [comment]
Lol guess I didn't do this. Thanks for adding it geohot! Fortunately the tests are pretty self documented so this issue should be in the clear.
