### ISSUE TITLE
install Capstone as dependency

### ISSUE THREAD

**Issue by aquynh** [BinaryAnalysisPlatform/qira#74]
from version **3.0.1**, it is possible to install Capstone engine just from PyPi, like:

    pip install capstone

unlike previous versions, this also downloads, compiles & builds the core (`libcapstone.so`), so it is no longer necessary to build & install the core separately like before. this means if you only use Capstone from Python, above command is enough to install everything you need to use Capstone.

**Comment by geohot** [comment]
oh awesome

**Comment by nedwill** [comment]
Yeah, this actually was my biggest issue with capstone even just using it for quick disassembly, e.g. in a CTF.

**Comment by geohot** [comment]
updated
