### ISSUE TITLE
Detect if BAP is already installed in install.sh

### ISSUE THREAD

**Issue by geohot** [BinaryAnalysisPlatform/qira#75]
If it is, don't reinstall it. Also, where is it coming from when you opam install?

**Comment by nedwill** [comment]
Pretty sure it's an official OPAM package: https://opam.ocaml.org/packages/bap/bap.0.9.3/

**Comment by nedwill** [comment]
And yeah, install.sh will have to be tightened up before 1.2.

**Comment by ivg** [comment]
yes, and if it is already installed, then it will finish with something like "BAP is already installed, nothing to do here"

**Comment by geohot** [comment]
Oh my bad, it works for me now
