### ISSUE TITLE
Please help :) using Qira over VM Guest > Host

### ISSUE THREAD

**Issue by Jidoja** [BinaryAnalysisPlatform/qira#78]
First things first I'm a huge fan of this utility and this is my first time ever posting on GIT anywhere so don't destroy me k?

I'm trying to run qira on a vm i have been working on with a kali distro on it. I have forwarded the correct ports and try to connect with my host machine's browser. I can get other server's or other utilities to work in this fashion with absolutely no problem. Is there something with Qira that I'm missing that I need to change in order for this to work? Again I'm a newbie so go easy especially if its crazy obvious lulz

**Comment by maverickwoo** [comment]
If you have just cloned the repo, `qira/middleware/qira_config.py` sets the network interface to bind to. My guess is you have left it at its default, which says `HOST = '127.0.0.1'`. If so, please change it to `HOST = '0.0.0.0'` and try again. And if this works, please close the issue. Thanks!
