### ISSUE TITLE
Assuming Python2

### ISSUE THREAD

**Issue by cganas** [BinaryAnalysisPlatform/qira#99]
Qira and the build process make a lot of assumptions that the `python` in path is `python2`. From an Arch linux experience, It would be great to have it explicitly reference `python2`.

**Comment by nedwill** [comment]
We'd be happy to support more distributions. It's probably easier for you to make the relevant patches as you've got your Arch environment already set up, so feel free to make those changes and submit a pull request.

**Comment by cganas** [comment]
Yeah, this patch wouldn't provide full support by any means. It is however a step in that direction. I'm working on it now.

**Comment by nedwill** [comment]
Ok great. Generally anything that strictly improves QIRA is an acceptable change.

**Comment by geohot** [comment]
fixed
